import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/app/_components/footer";
import { Navigation } from "@/app/_components/navigation";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navigation />
				<main className="pt-16">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
